import { icons, type LucideIcon } from "lucide-react";

interface NicheIconProps {
  iconName: string | null;
  className?: string;
  size?: number;
}

// Mapa de nomes de nicho → ícones lucide (portado do sistema Boder)
const iconMap: Record<string, LucideIcon> = {
  folder: icons.Folder,
  store: icons.Store,
  shirt: icons.Shirt,
  sparkles: icons.Sparkles,
  shopping_bag: icons.ShoppingBag,
  shopping_cart: icons.ShoppingCart,
  laptop: icons.Laptop,
  smartphone: icons.Smartphone,
  monitor: icons.Monitor,
  home: icons.House,
  heart: icons.Heart,
  star: icons.Star,
  coffee: icons.Coffee,
  utensils: icons.Utensils,
  car: icons.Car,
  plane: icons.Plane,
  camera: icons.Camera,
  music: icons.Music,
  book: icons.BookOpen,
  graduation_cap: icons.GraduationCap,
  briefcase: icons.Briefcase,
  building: icons.Building,
  factory: icons.Factory,
  dumbbell: icons.Dumbbell,
  pill: icons.Pill,
  stethoscope: icons.Stethoscope,
  palette: icons.Palette,
  scissors: icons.Scissors,
  wrench: icons.Wrench,
  hammer: icons.Hammer,
  zap: icons.Zap,
  flame: icons.Flame,
  leaf: icons.Leaf,
  flower: icons.Flower2,
  sun: icons.Sun,
  moon: icons.Moon,
  cloud: icons.Cloud,
  droplet: icons.Droplet,
  gem: icons.Gem,
  crown: icons.Crown,
  gift: icons.Gift,
  cake: icons.Cake,
  baby: icons.Baby,
  dog: icons.Dog,
  cat: icons.Cat,
  paw_print: icons.PawPrint,
  globe: icons.Globe,
  map: icons.Map,
  compass: icons.Compass,
  anchor: icons.Anchor,
  rocket: icons.Rocket,
  trophy: icons.Trophy,
  medal: icons.Medal,
  target: icons.Target,
  shoe: icons.Footprints,
  watch: icons.Watch,
  glasses: icons.Glasses,
  cpu: icons.Cpu,
  hard_drive: icons.HardDrive,
  wifi: icons.Wifi,
  bluetooth: icons.Bluetooth,
  battery: icons.Battery,
  wine: icons.Wine,
  beer: icons.Beer,
  pizza: icons.Pizza,
  apple: icons.Apple,
  cherry: icons.Cherry,
  bike: icons.Bike,
  waves: icons.Waves,
  mountain: icons.Mountain,
  tent: icons.Tent,
  wallet: icons.Wallet,
  credit_card: icons.CreditCard,
  banknote: icons.Banknote,
  chart: icons.ChartBar,
  trending_up: icons.TrendingUp,
  mail: icons.Mail,
  phone: icons.Phone,
  message: icons.MessageCircle,
  users: icons.Users,
  brush: icons.Brush,
  pen: icons.PenTool,
  image: icons.Image,
  video: icons.Video,
  sofa: icons.Armchair,
  lamp: icons.Lamp,
  bed: icons.Bed,
  bath: icons.Bath,
  key: icons.Key,
  lock: icons.Lock,
  tree: icons.TreePine,
  bird: icons.Bird,
  fish: icons.Fish,
  bug: icons.Bug,
};

export function NicheIcon({ iconName, className = "w-4 h-4", size }: NicheIconProps) {
  const normalizedName = iconName?.toLowerCase().replace(/-/g, "_") || "folder";
  const IconComponent = iconMap[normalizedName] || icons.Folder;
  return <IconComponent className={className} size={size} />;
}
